### ISSUE TITLE
$dx_black_menu = 1 causes a crash before endgame.

### ISSUE THREAD

**Issue by DarkRTA** [hmxmilohax/rock-band-3-deluxe#519] opened 2024-02-02 20:39 UTC

**Comment by jnackmclain** [comment] 2024-03-06 00:31
Not fixed but I did find no menu background + no song transitions is the cause of the crash.

**Comment by jnackmclain** [comment] 2024-03-06 03:38
fixed in latest dev

**Closed as completed by jnackmclain** 2024-03-06 03:38 UTC
Labels: bug
