### ISSUE TITLE
Latest version with merged Pro Charts crash game on song load (RPCS3)

### ISSUE THREAD

**Issue by carlmylo** [hmxmilohax/rock-band-3-deluxe#86] opened 2023-01-01 11:37 UTC
Loading in the latest version of RB3DX via RPCS3 and selecting certain songs with Pro charts cause the game to crash. Tried with 2112 and Green Day songs and RPCS3 spits out a "The PS3 application has likely crashed RPCS3" error. This happens every time the song is loaded.

I have reinitialized the repo to get a cleaner installation and it seems to happen regardless, and it happened to someone else with a similar installation.

**Comment by jnackmclain** [comment] 2023-01-01 16:32
I have tried loading every 2112 version in:

* Xenia
* RPCS3
* RPCS3 but this time using pro guitar

None of them crashed.

**Comment by jnackmclain** [comment] 2023-01-01 16:33
I also tried without, and with installing the original rb3 pro pack

**Comment by jnackmclain** [comment] 2023-01-01 22:52
Actually we found this issue, and the cause, it is fixed as of [d8d90ca](https://github.com/hmxmilohax/rock-band-3-deluxe/commit/d8d90cae68db160ed07891d36e896f7d80674606)

**Closed as completed by jnackmclain** 2023-01-01 22:52 UTC
