### ISSUE TITLE
BRE lanes bugged when using custom color setup

### ISSUE THREAD

**Issue by wintyre01** [hmxmilohax/rock-band-3-deluxe#593] opened 2024-03-24 15:33 UTC
**Describe the bug**
The lanes in the Big Rock Endings of tracks shift over to the right if using anything outside the normal color setup, while lanes outside of that are just fine.

**To Reproduce**
1. Go to Deluxe Settings, Customize Track Theme
2. Change Colors to anything outside of standard GRYBO (RYBG for Drums)
3. Pick a song with a BRE
4. All BRE lanes shift to the right

**Expected behavior**
Lanes should still show up all across the track in BRE 

**Screenshots** (From RPCS3, but the same result occurs on Xbox 360 hardware)
BRE Lanes:
<img width="898" alt="BRE Lane Error" src="https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143204241/99cc39a2-ba5d-44db-bd72-5e1c96c5d86c">
Regular Lanes:
<img width="898" alt="Regular Lanes" src="https://github.com/hmxmilohax/rock-band-3-deluxe/assets/143204241/41f9b2fd-c087-45d9-94d2-a6c4e916d129">

**DX Settings** (These are from RPCS3 build. 360 hardware should be the same but I can send those as well if needed)
- [dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14735917/dx_settings.txt)
- [dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14735921/dx_modifiers.txt)
- [dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14735923/dx_values.txt)

**Game Information**
 - Platform: All (tested on Xbox 360 & RPCS3)
 - Version: 1.1.0-beta5
 - Song Count: 4158 (Xbox 360)/4235 (RPCS3)

**Additional context**
As mentioned before and as shown in the screenshots, this does not affect lanes outside of the BRE for some reason

**Comment by glitchgod0** [comment] 2024-03-24 15:39
This is a known bug, we cant do much about it yet

**Comment by DarkRTA** [comment] 2024-03-24 15:43
duplicate of #407

**Closed as not planned by DarkRTA** 2024-03-24 15:43 UTC
Labels: bug
