### ISSUE TITLE
countdown fucks with tambourine solos

### ISSUE THREAD

**Issue by exoticri** [hmxmilohax/rock-band-3-deluxe#435] opened 2023-10-21 21:24 UTC
if a countdown pops up during a tambourine solo, the percentage for the solo disappears
![image](https://github.com/hmxmilohax/rock-band-3-deluxe/assets/101082423/3c14ce52-c39c-4094-b0ed-970dbb57f002)
it

**Comment by jnackmclain** [comment] 2023-10-21 21:29
duplicate of #400 
This is because it is reading the harm track for midi parser so this section is blank, indicating a countdown should trigger

**Closed as completed by jnackmclain** 2023-10-21 21:29 UTC
Labels: bug, duplicate
