### ISSUE TITLE
RB3DX YARG Song Updates Issues

### ISSUE THREAD

**Issue by CorndogWaterGrab** [hmxmilohax/rock-band-3-deluxe#629] opened 2024-04-21 00:14 UTC
Not sure if this is the proper place to report this, but I noticed two issues when using the song update pack for YARG

Hello There - The chart starts a few seconds after the audio and is at a slower bpm

Them Bones - The chart is at a much faster bpm than the audio causing the notes to all be extremely close together.

Both songs worked properly upon removing their entries in the updates folder, albeit without the additional features.

**Comment by T3HM3T4L** [comment] 2024-04-30 16:50
I too am unaware of a better place to report issues regarding the song_updates which I use in YARG.

I receive an error regarding beforeiforget:

/home/.../Slipknot - Before I Forget - Node beforeiforget
At least one track fails midi spec for containing multiple unique track names (thus making it ambiguous) - Thrown by a midi update

I just grabbed the latest version of the song_updates for YARG (mine was massively out of date and a lot smaller) which fixed the same issue I just described with seasonsintheabyss, but beforeiforget's error remains.

**Comment by jnackmclain** [comment] 2024-06-03 19:26
@exoticri are you able to look into this one?

**Comment by r0bd0g** [comment] 2024-06-03 21:06
beforeiforget has a busted track names, I mentioned that in the discord after this issue was opened.

**Comment by jnackmclain** [comment] 2024-06-03 21:08
please try to keep information like this in the issues so they dont get lost

**Comment by r0bd0g** [comment] 2024-06-03 21:09
The error message given by the reporter makes it pretty clear what the problem is anyway.

**Comment by jnackmclain** [comment] 2024-06-03 21:38
These have all been fixed in latest develop. The official yarg updates zip will update on next beta push, or you can get it now here from my tested action

https://github.com/hmxmilohax/rock-band-3-deluxe/actions/runs/9357524130/artifacts/1564432457

**Closed as completed by jnackmclain** 2024-06-03 21:38 UTC
Labels: bug
