### ISSUE TITLE
Festival Venues Crashing

### ISSUE THREAD

**Issue by dirkNlerxst** [hmxmilohax/rock-band-3-deluxe#614] opened 2024-04-08 19:12 UTC
**Describe the bug**
If a festival venue is in rotation (forced or random), the game crashes.

**To Reproduce**
1. Set Festival Venues via Venue Options
2. Select Song/Inst/Diff
3. Loading tips and song transition plays
4. Crash

**Expected behavior**
Loading festival venues.

**Screenshots**
N/A

**DX Settings**
- `dx_settings.dta`: [dx_settings.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14910025/dx_settings.txt)
- `dx_modifiers.dta`: [dx_modifiers.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14910024/dx_modifiers.txt)
- `dx_values.dta`: [dx_values.txt](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14910026/dx_values.txt)

**Game Information**
 - Platform: RPCS3 16299-412db758
 - Version:1.1.0-nightly+328912c2e
 - Song Count: 4292

**Additional context**
Before it was actually crashing on loading tips but I can't seem to reproduce that and does do loading tips/song transition...

[RPCS3.log](https://github.com/hmxmilohax/rock-band-3-deluxe/files/14910179/RPCS3.log)

**Comment by jnackmclain** [comment] 2024-04-08 19:14
ensure you have debug console mode and high memory mode enabled

**Comment by dirkNlerxst** [comment] 2024-04-08 19:17
> ensure you have debug console mode and high memory mode enabled

I can confirm both of these are on. Also RPCS3.log re-added sorry about that.

**Comment by DarkRTA** [comment] 2024-04-08 19:58
closing as invalid as its caused by a bad rpcs3 config

**Closed as not planned by DarkRTA** 2024-04-08 19:58 UTC
Labels: bug, invalid, RPCS3
